### ISSUE TITLE
block implicitly retains self

### ISSUE THREAD

**Issue by wtholliday** [ollix/MetalNanoVG#20] opened 2019-07-18 14:28 UTC
I'm getting this warning:

```
nanovg_mtl.m:1387:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
      dispatch_semaphore_signal(_semaphore);
                                ^
                                self->
```

Easy to fix :)

**Comment by olliwang** [comment] 2019-08-17 18:02
I couldn't reproduce the same warning on Xcode 11 beta 5. What Xcode version do you use?

**Comment by wtholliday** [comment] 2019-08-18 04:52
@olliwang Version 10.3 (10G8)

**Comment by olliwang** [comment] 2019-08-18 08:36
Thanks. Fixed in d3e0fc65180f6f2cb1a9.

**Closed as completed by olliwang** 2019-08-18 08:36 UTC
